org: wildflowerschools
app: wf-airtable-api
service: wf-airtable-api-server

frameworkVersion: '4'

useDotenv: true

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  timeout: 30
  environment:
    AIRTABLE_ACCESS_TOKEN: ${env:AIRTABLE_ACCESS_TOKEN}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    GOOGLE_CLOUD_API_KEY: ${env:GOOGLE_CLOUD_API_KEY}
    AIRTABLE_SCHOOL_DB_BASE_ID: ${env:AIRTABLE_SCHOOL_DB_BASE_ID, null}
    STAGE: ${self:provider.stage}

functions:
  api:
    handler: app.main.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements
