from app import const

BASE_ID = const.AIRTABLE_SCHOOL_DB_BASE_ID

HUBS_TABLE_NAME = 'Hubs'
PODS_TABLE_NAME = 'Pods'
SCHOOLS_TABLE_NAME = 'Schools'
EDUCATORS_TABLE_NAME = 'Educators'
PARTNERS_TABLE_NAME = 'Partners'
GUIDES_SCHOOLS_TABLE_NAME = 'Guides x Schools'
EDUCATORS_SCHOOLS_TABLE_NAME = 'Educators x Schools'
MONTESSORI_CERTIFICATIONS_TABLE_NAME = 'Montessori Certifications'
LANGUAGES_TABLE_NAME = 'Languages'
CONTACT_INFO_TABLE_NAME = 'Contact Info'
SOCIO_ECONOMIC_BACKGROUNDS_TABLE_NAME = 'SocioEconomic Background'
FIELD_CATEGORIES_TABLE_NAME = 'Field Categories'
FIELD_MAPPING_TABLE_NAME = 'Field Mapping'
SSJ_TYPEFORM_RESPONSES_TABLE_NAME = 'SSJ Typeforms: Start a School'
